### ISSUE TITLE
Add visualizations to notebook

### ISSUE THREAD

**Issue by amitSA** [catherinelee274/fraud_detection#24]
Visualizations that show patterns between our features and output labels. 

Todo:
- [x] ROC Curve
- [x] Confusion Matrices
- [x] consolidated classification report
- [x] graphviz library for decision-trees and xgboost models

**Comment by catherinelee274** [comment]
Specifically roc curve and confusion matrices

**Comment by amitSA** [comment]
make sure you add graphviz to the pipfile

**Comment by amitSA** [comment]
@catherinelee274  consolidated classification report in a separate PR
